# Site settings
title: Simulacrum Blog
description: >
  Various topics, mostly focused on Rust development.
baseurl: "/"
url: "https://Mark-Simulacrum.github.io"
logo: "/images/logo.png"
github_username: Mark-Simulacrum

# Build settings
highlighter: rouge

root: "https://Mark-Simulacrum.github.io"
