# Site settings
title: Mark Rousskov's Blog
description: >
  Various topics, mostly focused on Rust development.
baseurl: ""
url: "https://mark.rousskov.org/blog"
logo: "images/logo.png"
github_username: Mark-Simulacrum

# Build settings
highlighter: rouge

root: "https://mark.rousskov.org/blog/"
